apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agrobd-pdb
  namespace: agrobd
spec:
  minAvailable: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - agrobd

