apiVersion: v1
kind: Secret
metadata:
  name: agrobd-secret
  namespace: agrobd
type: Opaque
stringData:
  #DB_HOST: '192.168.10.213'
  DB_HOST: 'mariadb-service.mariadb.svc.cluster.local'  # <-- cluster DNS
  DB_DATABASE: 'bat_crm_uat'
  DB_USERNAME: 'batcrmuat'
  DB_PASSWORD: '12345'